<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>AliceCoopLauncher</AssemblyName>
    <RootNamespace>AliceCoopLauncher</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <Deterministic>true</Deterministic>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ApplicationIcon>Assets\AliceCoop.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\images\aliceWhait.png">
      <Link>Assets\aliceWhait.png</Link>
    </Resource>
    <Resource Include="..\images\AliceLauncher.jpg">
      <Link>Assets\AliceLauncher.jpg</Link>
    </Resource>
  </ItemGroup>
</Project>
